server:
  address: 0.0.0.0
  port: ${PORT:8081}
spring:
  resources:
    static-locations=classpath : /static/
  config:
    import: optional:secrets.properties
  cache.type: caffeine
  cache.caffeine.spec: maximumSize=1000,expireAfterAccess=5m
  thymeleaf :
    enabled: true
    cache: false
  mvc:
    locale.resolver: fixed
    static-path-pattern: /static/**
  jpa:
    hibernate.ddl-auto=update:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chess_db?user=root&password=root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mail:
    host: smtp.zoho.eu
    port: 587
    protocol: smtp
    debug: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true