spring.config.import: optional:secrets.properties

server:
  port: ${PORT:8081}

spring:
  cache.type: caffeine
  cache.caffeine.spec: maximumSize=1000,expireAfterAccess=5m
  thymeleaf.cache: false
  mvc.locale.resolver: fixed
  jpa:
    hibernate.ddl-auto=update:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chessdb
  mail:
    host: smtp.zoho.eu
    port: 587
    protocol: smtp
    debug: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

