server:
  port: ${PORT:8081}

spring:
  thymeleaf.cache: false
  mvc.locale.resolver: fixed
  h2.console.enable: true
  h2.console.path: /db
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:h2:mem:online_chess
    username: sa
    password: s3CR3T
    h2:
      console:
        enabled: true
        path: /h2-console
