version: "3"
services:
  mysqldb:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chess_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080